apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: intranet
  labels:
    app: mysql
    app.kubernetes.io/part-of: omniflowti
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_DATABASE: "intranet_flowti"
  MYSQL_USER: "flowti"
  MYSQL_PASSWORD: "flowtipass"
