apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: intranet
  labels:
    app: mysql
    app.kubernetes.io/part-of: intranet-portal
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_DATABASE: "intranet_db"
  MYSQL_USER: "intranet"
  MYSQL_PASSWORD: "intranetpass"
