apiVersion: v1
kind: ConfigMap
metadata:
  name: intranet-config
  namespace: intranet
  labels:
    app: intranet-app
    app.kubernetes.io/part-of: omniflowti
data:
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_NAME: "intranet_flowti"
  APP_ENV: "production"
  APP_URL: "http://intranet.local"
  SESSION_LIFETIME: "7200"
  LDAP_ENABLED: "false"
