apiVersion: v1
kind: Secret
metadata:
  name: intranet-secret
  namespace: intranet
  labels:
    app: intranet-app
    app.kubernetes.io/part-of: omniflowti
type: Opaque
stringData:
  DB_USER: "root"
  DB_PASS: "rootpass"
  APP_SECRET: "flowti-prod-secret-k8s-cluster-2026-portal"
